# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd server && npm i    
    - run: cd server && npm run build:ui --if-present
    - run: cd server && npm test

    # Deployment to DigitalOcean droplet
    - name: Deploy to DigitalOcean
      if: github.event_name == 'push' && matrix.node-version == '18.x'
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        DO_HOST: ${{ secrets.DO_HOST }}
        DO_USERNAME: ${{ secrets.DO_USERNAME }}
      run: |
        echo "$DO_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r ./ $DO_USERNAME@$DO_HOST:~/CRnode
        ssh -i private_key.pem $DO_USERNAME@$DO_HOST "cd ~/CRnode/server && npm run build:ui && pm2 restart 3"
        rm -f private_key.pem
