name: CloudRounds CI/CD

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Add DO Droplet to SSH known hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "142.93.60.189 $(ssh-keyscan 142.93.60.189 2>/dev/null)" >> ~/.ssh/known_hosts

    - name: Deploy to DigitalOcean
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        DO_HOST: ${{ secrets.DO_HOST }}
        DO_USERNAME: ${{ secrets.DO_USERNAME }}
      run: |
        echo "$DO_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r * deployer@142.93.60.189:~/CRnode/
        ssh -i private_key.pem deployer@142.93.60.189 "cd ~/CRnode/server && npm run build:ui && pm2 restart 0"
        rm -f private_key.pem
